<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-B9KJEIH" failures="1" tests="4" name="Test" time="24.166" errors="0" timestamp="2022-10-12T16:15:37 IST">
  <testcase classname="com.SauceDemo.TestClass.TC01_VerifyLoginFunctionality" name="verifyLoginFunctionality" time="0.749"/>
  <testcase classname="com.SauceDemo.TestClass.TC03_VerifyBagProductFunctionality" name="verifyBagProductFunctionality" time="1.74"/>
  <testcase classname="com.SauceDemo.TestClass.TC02_VerifyLogOutFunctionality" name="verifyLOgOutFunctionality" time="1.838"/>
  <testcase classname="com.SauceDemo.TestClass.TC04_VerifyAllProductFunctionality" name="verifyAllProductFunctionality" time="2.178">
    <failure type="java.lang.AssertionError" message="expected [6] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [3]
at com.SauceDemo.TestClass.TC04_VerifyAllProductFunctionality.verifyAllProductFunctionality(TC04_VerifyAllProductFunctionality.java:34)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyAllProductFunctionality -->
</testsuite> <!-- Test -->
